/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import koneksi.Koneksi;
import javax.swing.*;
import java.awt.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;


public class FormDashboard extends javax.swing.JFrame {

    /**
     * Creates new form FormDashboard
     */
    public FormDashboard() {
        initComponents();
        tampilkanTanggalHariIni();
        tampilkanDataTransaksi();
        tampilkanGrafikPenjualan(); 
    }
    
    // Menampilkan tanggal hari ini
private void tampilkanTanggalHariIni() {
    SimpleDateFormat sdf = new SimpleDateFormat("EEEE, dd MMMM yyyy");
    Date sekarang = new Date();
    labelTanggal.setText(sdf.format(sekarang));
}

// Menampilkan total pendapatan dan jumlah transaksi dari tabel laporan_transaksi
private void tampilkanDataTransaksi() {
    try {
        Connection con = Koneksi.getConnection();
        String sql = "SELECT COUNT(*) AS jumlah, SUM(total) AS total FROM transaksi_new";
        Statement st = con.createStatement();
        
        // Tidak perlu casting ResultSet
        ResultSet rs = st.executeQuery(sql);

        if (rs.next()) {
            int jumlah = rs.getInt("jumlah");
            double total = rs.getDouble("total");

            labelJumlah.setText(jumlah + " Transaksi");
            labelTotal.setText("Rp " + String.format("%,.0f", total));
        }

        rs.close();
        st.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data transaksi: " + e.getMessage());
    }
}

// Menampilkan grafik penjualan dari tabel laporan_transaksi
private void tampilkanGrafikPenjualan() {
    try {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        Connection con = Koneksi.getConnection();
        String sql = "SELECT tanggal, SUM(total) as total FROM transaksi_new GROUP BY tanggal ORDER BY tanggal DESC LIMIT 7";
        Statement st = con.createStatement();
        
        // Tidak perlu casting ResultSet
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            String tanggal = rs.getString("tanggal");
            double total = rs.getDouble("total");
            dataset.addValue(total, "Penjualan", tanggal);
        }

        JFreeChart chart = ChartFactory.createLineChart(
            "Grafik Penjualan Mingguan", "Tanggal", "Total Penjualan",
            dataset, PlotOrientation.VERTICAL, false, true, false
        );

        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(jPanelGrafik.getWidth(), jPanelGrafik.getHeight()));
        jPanelGrafik.removeAll();
        jPanelGrafik.setLayout(new BorderLayout());
        jPanelGrafik.add(chartPanel, BorderLayout.CENTER);
        jPanelGrafik.validate();

        rs.close();
        st.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat grafik: " + e.getMessage());
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelTanggal = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jPanelGrafik = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelTotal1 = new javax.swing.JLabel();
        labelJumlah1 = new javax.swing.JLabel();
        labelJumlah = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnFormProduk = new javax.swing.JButton();
        btnFormTransaksi = new javax.swing.JButton();
        btnFormLaporanTransaksi = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("SELAMAT DATANG ");

        labelTanggal.setText("Tanggal Hari ini");

        labelTotal.setText("Total");

        javax.swing.GroupLayout jPanelGrafikLayout = new javax.swing.GroupLayout(jPanelGrafik);
        jPanelGrafik.setLayout(jPanelGrafikLayout);
        jPanelGrafikLayout.setHorizontalGroup(
            jPanelGrafikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        jPanelGrafikLayout.setVerticalGroup(
            jPanelGrafikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        jLabel2.setText("Tanggal Hari Ini");

        labelTotal1.setText("Total");

        labelJumlah1.setText("Jumlah Transaksi");

        labelJumlah.setText("Jumlah Transaksi");

        btnDashboard.setBackground(new java.awt.Color(51, 255, 204));
        btnDashboard.setText("Dahboard");

        btnFormProduk.setBackground(new java.awt.Color(0, 255, 204));
        btnFormProduk.setText("Form Produk");
        btnFormProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormProdukActionPerformed(evt);
            }
        });

        btnFormTransaksi.setBackground(new java.awt.Color(0, 255, 204));
        btnFormTransaksi.setText("FormTransaksi");
        btnFormTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormTransaksiActionPerformed(evt);
            }
        });

        btnFormLaporanTransaksi.setBackground(new java.awt.Color(0, 255, 204));
        btnFormLaporanTransaksi.setText("Form Laporan Transaksi");
        btnFormLaporanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormLaporanTransaksiActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(btnFormProduk)
                        .addGap(18, 18, 18)
                        .addComponent(btnFormTransaksi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFormLaporanTransaksi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(btnDashboard))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTanggal)
                                    .addComponent(jLabel2))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTotal))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelJumlah)
                                    .addComponent(labelJumlah1))
                                .addGap(142, 142, 142))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelGrafik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnDashboard)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogout)
                            .addComponent(btnFormLaporanTransaksi)
                            .addComponent(btnFormTransaksi)
                            .addComponent(btnFormProduk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(labelTotal1)
                            .addComponent(labelJumlah1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTanggal)
                            .addComponent(labelTotal)
                            .addComponent(labelJumlah))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel6))
                    .addComponent(jPanelGrafik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormTransaksiActionPerformed
        // TODO add your handling code here:
        FormTransaksi formTransaksi = new FormTransaksi();
        formTransaksi.setVisible(true);
        this.dispose(); // Tutup dashboard
    }//GEN-LAST:event_btnFormTransaksiActionPerformed

    private void btnFormProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormProdukActionPerformed
        // TODO add your handling code here:
         FormProduk formProduk = new FormProduk();
         formProduk.setVisible(true);
         this.dispose(); // Tutup dashboard
    }//GEN-LAST:event_btnFormProdukActionPerformed

    private void btnFormLaporanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormLaporanTransaksiActionPerformed
        // TODO add your handling code here:
        FormLaporanTransaksi formLaporan = new FormLaporanTransaksi();
        formLaporan.setVisible(true);
        this.dispose(); // Tutup dashboard
    }//GEN-LAST:event_btnFormLaporanTransaksiActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        FormLogin login = new FormLogin();
        login.setVisible(true);
        this.dispose(); // Tutup dashboard
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnFormLaporanTransaksi;
    private javax.swing.JButton btnFormProduk;
    private javax.swing.JButton btnFormTransaksi;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelGrafik;
    private javax.swing.JLabel labelJumlah;
    private javax.swing.JLabel labelJumlah1;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelTotal1;
    // End of variables declaration//GEN-END:variables
}
