/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Connection;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellEditor;
import java.sql.PreparedStatement;


public class FormProduk extends javax.swing.JFrame {
    private TableCellEditor defaultEditor; // ✅ Disimpan di sini
 
    public FormProduk() {
        initComponents();
        tampilkanData(); // menampilkan data saat form dibuka
        setLocationRelativeTo(null);
        setTitle("Manajemen Produk");
        tabelProduk.setDefaultEditor(Object.class, null);
        
        // Tambahkan listener klik baris tabel
    tabelProduk.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int selectedRow = tabelProduk.getSelectedRow();
            if (selectedRow != -1) {
                String id = tabelProduk.getValueAt(selectedRow, 0).toString();
                String nama = tabelProduk.getValueAt(selectedRow, 1).toString();
                String harga = tabelProduk.getValueAt(selectedRow, 2).toString();
                String stok = tabelProduk.getValueAt(selectedRow, 3).toString();

                txtID.setText(id);
                txtproduk.setText(nama);
                txtharga.setText(harga);
                txtStok.setText(stok);
                txtID.setEnabled(false);  // jangan izinkan ubah ID
            }
        }
    });
    }
    

    private void tampilkanData() {
        DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Produk");
    model.addColumn("Nama Produk");
    model.addColumn("Harga");
    model.addColumn("Stok");

    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kasir", "root", "");
        Statement stmt = con.createStatement();
        var rs = stmt.executeQuery("SELECT * FROM produk_new");

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_produk"),
                rs.getString("nama_produk"),
                rs.getString("harga"),
                rs.getString("stok")
            });
        }

        tabelProduk.setModel(model);

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal mengambil data: " + e.getMessage());
    }
    }
    private void resetForm() {
    txtID.setText("");
    txtproduk.setText("");
    txtharga.setText("");
    txtStok.setText("");
    txtID.setEnabled(true);
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        txtKodeproduk = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        txtHarga = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtproduk = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProduk = new javax.swing.JTable();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btnbersihkan = new javax.swing.JButton();
        txtstok = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        btnFormDashboard = new javax.swing.JButton();
        btnFormTransaksi = new javax.swing.JButton();
        btnFormLaporanTransaksi = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtKodeproduk.setText("id produk :");

        jLabel2.setText("MANAJEMEN PRODUK");

        txtNama.setText("nama produk :");

        txtHarga.setText("harga :");

        txtID.setPreferredSize(new java.awt.Dimension(84, 22));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodukActionPerformed(evt);
            }
        });

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });

        btnsimpan.setText("simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        tabelProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelProdukMouseClicked(evt);
            }
        });
        tabelProduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelProdukKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelProduk);

        btnubah.setText("ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnhapus.setText("hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnkeluar.setText("keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        btnbersihkan.setText("bersihkan");
        btnbersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbersihkanActionPerformed(evt);
            }
        });

        txtstok.setText("stok :");

        txtStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokActionPerformed(evt);
            }
        });

        btnFormDashboard.setBackground(new java.awt.Color(0, 255, 204));
        btnFormDashboard.setText("Dashboard");
        btnFormDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormDashboardActionPerformed(evt);
            }
        });

        btnFormTransaksi.setBackground(new java.awt.Color(0, 255, 204));
        btnFormTransaksi.setText("Form Transaksi");
        btnFormTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormTransaksiActionPerformed(evt);
            }
        });

        btnFormLaporanTransaksi.setBackground(new java.awt.Color(0, 255, 204));
        btnFormLaporanTransaksi.setText("Form Laporan Transaksi");
        btnFormLaporanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormLaporanTransaksiActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(btnFormDashboard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnubah)
                                .addGap(37, 37, 37)
                                .addComponent(btnhapus)
                                .addGap(41, 41, 41)
                                .addComponent(btnbersihkan)
                                .addGap(45, 45, 45)
                                .addComponent(btnkeluar))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnFormTransaksi)
                                        .addGap(35, 35, 35)
                                        .addComponent(btnFormLaporanTransaksi))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtKodeproduk)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNama)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHarga)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtstok)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 100, Short.MAX_VALUE)))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnFormDashboard)
                    .addComponent(btnLogout)
                    .addComponent(btnFormLaporanTransaksi)
                    .addComponent(btnFormTransaksi))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKodeproduk)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama)
                    .addComponent(txtproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHarga)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstok)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btnubah)
                    .addComponent(btnhapus)
                    .addComponent(btnkeluar)
                    .addComponent(btnbersihkan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodukActionPerformed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabelProduk.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih salah satu baris di tabel terlebih dahulu.");
        return;
    }

    String id = txtID.getText();  // Dari field, karena sudah diisi otomatis
    String nama = txtproduk.getText();
    String harga = txtharga.getText();
    String stok = txtStok.getText();

    if (nama.isEmpty() || harga.isEmpty() || stok.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Silakan lengkapi semua field sebelum menyimpan.");
        return;
    }

    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kasir", "root", "");

        String updateQuery = "UPDATE produk_new SET nama_produk=?, harga=?, stok=? WHERE id_produk=?";
        PreparedStatement stmt = con.prepareStatement(updateQuery);  // ✅ TANPA CASTING
        stmt.setString(1, nama);
        stmt.setString(2, harga);
        stmt.setString(3, stok);
        stmt.setString(4, id);

        int rowsUpdated = stmt.executeUpdate();

        if (rowsUpdated > 0) {
            // Perbarui tampilan tabel juga
            DefaultTableModel model = (DefaultTableModel) tabelProduk.getModel();
            model.setValueAt(nama, selectedRow, 1);
            model.setValueAt(harga, selectedRow, 2);
            model.setValueAt(stok, selectedRow, 3);

            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui.");
            resetForm();// mengosongkan input field setelah update
            tampilkanData(); // refresh isi tabel dari database
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error saat update: " + e.getMessage());
    }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnbersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbersihkanActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
        txtproduk.setText("");
        txtharga.setText("");
        txtStok.setText("");
    }//GEN-LAST:event_btnbersihkanActionPerformed

    private void txtStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText();
         String nama = txtproduk.getText();
         String harga = txtharga.getText();
         String stok = txtStok.getText();

    try {
        // 1. Koneksi ke database
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kasir", "root", ""); // ganti sesuai koneksi database kamu

        // 2. Query insert data
        String query = "INSERT INTO produk_new (id_produk, nama_produk, harga, stok) VALUES ('" + id + "', '" + nama + "', '" + harga + "', '" + stok + "')";

        Statement stmt = con.createStatement();
        stmt.executeUpdate(query);

        // 3. Tampilkan juga ke tabel (opsional)
        DefaultTableModel model = (DefaultTableModel) tabelProduk.getModel();
        model.addRow(new Object[]{id, nama, harga, stok});

        // 4. Bersihkan form
        btnbersihkanActionPerformed(null);

        JOptionPane.showMessageDialog(this, "Data berhasil disimpan ke database.");

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
    }
         
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        int row = tabelProduk.getSelectedRow();

    if (row >= 0) {
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                String id = tabelProduk.getValueAt(row, 0).toString();

                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kasir", "root", "");
                String query = "DELETE FROM produk_new WHERE id_produk=?";
                PreparedStatement stmt = con.prepareStatement(query);
                stmt.setString(1, id);
                int deleted = stmt.executeUpdate();

                if (deleted > 0) {
                    DefaultTableModel model = (DefaultTableModel) tabelProduk.getModel();
                    model.removeRow(row);
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
                } else {
                    JOptionPane.showMessageDialog(this, "Data gagal dihapus dari database.");
                }

                stmt.close();
                con.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus");
    }
       
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void tabelProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelProdukMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelProdukMouseClicked
private void updateRowInTable(String id, String nama, String harga, String stok) {
    DefaultTableModel model = (DefaultTableModel) tabelProduk.getModel();

    for (int i = 0; i < model.getRowCount(); i++) {
        if (model.getValueAt(i, 0).toString().equals(id)) {
            model.setValueAt(nama, i, 1);
            model.setValueAt(harga, i, 2);
            model.setValueAt(stok, i, 3);
            break;
        }
    }
}
    private void tabelProdukKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelProdukKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelProdukKeyPressed

    private void btnFormDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormDashboardActionPerformed
        // TODO add your handling code here:
        FormDashboard dashboard = new FormDashboard();
        dashboard.setVisible(true);
        this.dispose(); //Tutup produk
    }//GEN-LAST:event_btnFormDashboardActionPerformed

    private void btnFormTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormTransaksiActionPerformed
        // TODO add your handling code here:
        FormTransaksi formTransaksi = new FormTransaksi();
        formTransaksi.setVisible(true);
        this.dispose(); //Tutup produk
    }//GEN-LAST:event_btnFormTransaksiActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        FormLogin login = new FormLogin();
        login.setVisible(true);
        this.dispose(); //Tutup produk
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnFormLaporanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormLaporanTransaksiActionPerformed
        // TODO add your handling code here:
        FormLaporanTransaksi formLaporan = new FormLaporanTransaksi();
        formLaporan.setVisible(true);
        this.dispose(); //Tutup produk
    }//GEN-LAST:event_btnFormLaporanTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormDashboard;
    private javax.swing.JButton btnFormLaporanTransaksi;
    private javax.swing.JButton btnFormTransaksi;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnbersihkan;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelProduk;
    private javax.swing.JLabel txtHarga;
    private javax.swing.JTextField txtID;
    private javax.swing.JLabel txtKodeproduk;
    private javax.swing.JLabel txtNama;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtproduk;
    private javax.swing.JLabel txtstok;
    // End of variables declaration//GEN-END:variables

}
