/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Connection;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import tampilan.FormLaporanTransaksi;
import java.sql.PreparedStatement;

public class FormTransaksi extends javax.swing.JFrame {
     DefaultTableModel model;
    Connection conn;
    int totalBayar = 0;

    public FormTransaksi() {
        initComponents();
        connect();         // koneksi database
        initTable(); // inisialisasi model dan hubungkan ke tabel
        setLocationRelativeTo(null);
        setTitle("Manajemen Produk");
    }
    private void connect() {
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/kasir", "root", "");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Koneksi gagal: " + e.getMessage());
    }
}
   
   private void initTable() {
    model = new DefaultTableModel();
    model.addColumn("ID Produk");
    model.addColumn("Nama Produk");
    model.addColumn("Harga");
    model.addColumn("Jumlah");
    model.addColumn("Tanggal");

    tabelTransaksi.setModel(model); // ini penting
}
private void resetForm() {
    txtID.setText("");
    txtproduk.setText("");
    txtharga.setText("");
    txtjumlah.setText("");
    jDateChooser1.setDate(null);
    txttotal.setText("");
    txtbayar.setText("");
    txtkembalian.setText("");
    txtID.setEnabled(true);
}
  



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdProduk = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnTambah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        txtTotal = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        txtCetakStruk = new javax.swing.JButton();
        txtJumlahBayar = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JLabel();
        txtkembalian = new javax.swing.JTextField();
        txtbayar = new javax.swing.JTextField();
        txtHarga = new javax.swing.JLabel();
        txtjumlah = new javax.swing.JTextField();
        txtNamaProduk = new javax.swing.JLabel();
        txtproduk = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        btnFormDashboard = new javax.swing.JButton();
        btnFormLaporanTransaksi = new javax.swing.JButton();
        btnFormProduk = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FORM TRANSAKSI");

        txtIdProduk.setText("ID Produk :");

        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDKeyPressed(evt);
            }
        });

        jLabel3.setText("Tanggal :");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        txtTotal.setText("Total :");

        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        txtCetakStruk.setText("Cetak Struk");
        txtCetakStruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCetakStrukActionPerformed(evt);
            }
        });

        txtJumlahBayar.setText("Jumlah Bayar :");

        txtKembalian.setText("Kembalian :");

        txtbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbayarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbayarKeyReleased(evt);
            }
        });

        txtHarga.setText("Harga :");

        txtjumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjumlahKeyReleased(evt);
            }
        });

        txtNamaProduk.setText("nama produk :");

        txtproduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprodukKeyReleased(evt);
            }
        });

        txtJumlah.setText("Jumlah :");

        txtharga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txthargaKeyReleased(evt);
            }
        });

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelTransaksi);

        btnFormDashboard.setBackground(new java.awt.Color(0, 255, 204));
        btnFormDashboard.setText("Dashboard");
        btnFormDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormDashboardActionPerformed(evt);
            }
        });

        btnFormLaporanTransaksi.setBackground(new java.awt.Color(0, 255, 204));
        btnFormLaporanTransaksi.setText("Form Laporan Transaksi");
        btnFormLaporanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormLaporanTransaksiActionPerformed(evt);
            }
        });

        btnFormProduk.setBackground(new java.awt.Color(0, 255, 204));
        btnFormProduk.setText("Form Produk");
        btnFormProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormProdukActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addComponent(txtCetakStruk, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnFormDashboard))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtIdProduk)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNamaProduk)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtproduk, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtHarga)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtJumlah))
                                    .addComponent(btnFormProduk))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, 0)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnFormLaporanTransaksi)
                                        .addGap(63, 63, 63))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 35, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTotal)
                                        .addGap(18, 18, 18)
                                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtJumlahBayar)
                                            .addComponent(txtKembalian))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnTambah)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBatal)))))
                        .addGap(8, 8, 8)
                        .addComponent(btnLogout)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnFormDashboard)
                    .addComponent(btnLogout)
                    .addComponent(btnFormLaporanTransaksi)
                    .addComponent(btnFormProduk))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdProduk)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txtHarga)
                        .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNamaProduk)
                        .addComponent(txtproduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtJumlah)
                        .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTambah)
                    .addComponent(btnBatal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJumlahBayar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKembalian)
                            .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtCetakStruk)))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText();
    String nama = txtproduk.getText();
    String harga = txtharga.getText();
    String jumlahStr = txtjumlah.getText();
    java.util.Date utilDate = jDateChooser1.getDate();   // Tanggal

    // Cek jika tanggal kosong
    if (utilDate == null) {
        JOptionPane.showMessageDialog(this, "Tanggal tidak boleh kosong.");
        return;
    }

    // Konversi ke SQL date
    java.sql.Date tanggal = new java.sql.Date(utilDate.getTime());

    // Validasi field lainnya
    if (id.isEmpty() || nama.isEmpty() || harga.isEmpty() || jumlahStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Lengkapi semua field terlebih dahulu.");
        return;
    }

    int jumlah = Integer.parseInt(jumlahStr);
    int hargaInt = Integer.parseInt(harga);
    int total = jumlah * hargaInt;
    
    model.addRow(new Object[]{id, nama, harga, jumlah, tanggal});

    // Hitung total semua item
    int totalBayar = 0;
    for (int i = 0; i < model.getRowCount(); i++) {
        int h = Integer.parseInt(model.getValueAt(i, 2).toString());
        int j = Integer.parseInt(model.getValueAt(i, 3).toString());
        totalBayar += h * j;
    }
    txttotal.setText(String.valueOf(totalBayar));
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
    txtjumlah.setText("");
    jDateChooser1.setDate(null);
    txttotal.setText("");
    txtkembalian.setText("");
    txtbayar.setText("");
    txtharga.setText("");
    jDateChooser1.setDate(null);
    model.setRowCount(0);
    int totalBayar = 0;
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtprodukKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprodukKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodukKeyReleased

    private void txtjumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlahKeyReleased

    private void txtCetakStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCetakStrukActionPerformed
        // TODO add your handling code here: 
         DefaultTableModel model = (DefaultTableModel) tabelTransaksi.getModel();
    if (model.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "Tidak ada transaksi untuk disimpan.");
        return;
    }

    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kasir", "root", "");

        System.out.println("===== STRUK PEMBELIAN =====");
        int totalKeseluruhan = 0;

        // Hitung total keseluruhan dulu
        for (int i = 0; i < model.getRowCount(); i++) {
            int harga = Integer.parseInt(model.getValueAt(i, 2).toString());
            int jumlah = Integer.parseInt(model.getValueAt(i, 3).toString());
            totalKeseluruhan += harga * jumlah;
        }

        // Ambil jumlah bayar dan hitung kembalian
        int bayar = Integer.parseInt(txtbayar.getText());
        int kembalian = bayar - totalKeseluruhan;

        // Simpan data dan cetak struk
        for (int i = 0; i < model.getRowCount(); i++) {
            String id = model.getValueAt(i, 0).toString();
            String nama = model.getValueAt(i, 1).toString();
            int harga = Integer.parseInt(model.getValueAt(i, 2).toString());
            int jumlah = Integer.parseInt(model.getValueAt(i, 3).toString());
            String tanggal = model.getValueAt(i, 4).toString();

            int subtotal = harga * jumlah;

            // Cetak per item
            System.out.println("Tanggal     : " + tanggal);
            System.out.println("ID Produk   : " + id);
            System.out.println("Nama Produk : " + nama);
            System.out.println("Harga       : " + harga);
            System.out.println("Jumlah      : " + jumlah);
            System.out.println("Subtotal    : " + subtotal);
            System.out.println("---------------------------");

            // Simpan ke database
            String insertQuery = "INSERT INTO transaksi_new (id_produk, nama_produk, harga, jumlah, tanggal, total, jumlah_bayar, kembalian) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(insertQuery);
            ps.setString(1, id);
            ps.setString(2, nama);
            ps.setInt(3, harga);
            ps.setInt(4, jumlah);
            ps.setString(5, tanggal);
            ps.setInt(6, subtotal); // total per item
            ps.setInt(7, bayar);
            ps.setInt(8, kembalian);
            ps.executeUpdate();
        }

        // Cetak total akhir dan kembalian
        System.out.println("Total Keseluruhan : " + totalKeseluruhan);
        System.out.println("Jumlah Dibayar    : " + bayar);
        System.out.println("Kembalian         : " + kembalian);
        System.out.println("===========================");
        System.out.println("Terima kasih telah berbelanja!\n");

        JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan dan struk dicetak.");

        // Bersihkan tabel dan form
        model.setRowCount(0);
        resetForm();

    } catch (SQLException | NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan transaksi: " + e.getMessage());
    }
        
    }//GEN-LAST:event_txtCetakStrukActionPerformed

    private void txthargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaKeyReleased

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txtIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyPressed
        // TODO add your handling code here:
        String id = txtID.getText();
    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kasir", "root", "");
        String query = "SELECT nama_produk, harga FROM produk_new WHERE id_produk = ?";
        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, id);
        ResultSet rs = (ResultSet) ps.executeQuery();

        if (rs.next()) {
            txtproduk.setText(rs.getString("nama_produk"));
            txtharga.setText(rs.getString("harga"));
        } else {
            txtproduk.setText("");
            txtharga.setText("");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal mengambil data produk: " + e.getMessage());
    }
    }//GEN-LAST:event_txtIDKeyPressed

    private void txtbayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbayarKeyPressed

    private void txtbayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbayarKeyReleased
        // TODO add your handling code here:
        try {
        int bayar = Integer.parseInt(txtbayar.getText());

        // Hitung total dari tabel seperti pada cetak struk
        DefaultTableModel model = (DefaultTableModel) tabelTransaksi.getModel();
        int totalKeseluruhan = 0;

        for (int i = 0; i < model.getRowCount(); i++) {
            int harga = Integer.parseInt(model.getValueAt(i, 2).toString());
            int jumlah = Integer.parseInt(model.getValueAt(i, 3).toString());
            totalKeseluruhan += harga * jumlah;
        }

        // Tampilkan total ke txttotal
        txttotal.setText(String.valueOf(totalKeseluruhan));

        int kembalian = bayar - totalKeseluruhan;
        txtkembalian.setText(String.valueOf(kembalian));
    } catch (NumberFormatException e) {
        txtkembalian.setText("0");
    }
    }//GEN-LAST:event_txtbayarKeyReleased

    private void btnFormDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormDashboardActionPerformed
        // TODO add your handling code here:
        FormDashboard dashboard = new FormDashboard();
        dashboard.setVisible(true);
        this.dispose(); //Tutup transaksi
    }//GEN-LAST:event_btnFormDashboardActionPerformed

    private void btnFormLaporanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormLaporanTransaksiActionPerformed
        // TODO add your handling code here:
        FormLaporanTransaksi formLaporan = new FormLaporanTransaksi();
        formLaporan.setVisible(true);
        this.dispose(); //Tutup transaksi
    }//GEN-LAST:event_btnFormLaporanTransaksiActionPerformed

    private void btnFormProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormProdukActionPerformed
        // TODO add your handling code here:
        FormProduk formProduk = new FormProduk();
         formProduk.setVisible(true);
         this.dispose(); // Tutup transaksi
    }//GEN-LAST:event_btnFormProdukActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        FormLogin login = new FormLogin();
        login.setVisible(true);
        this.dispose(); // Tutup transaksi
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnFormDashboard;
    private javax.swing.JButton btnFormLaporanTransaksi;
    private javax.swing.JButton btnFormProduk;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTambah;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JButton txtCetakStruk;
    private javax.swing.JLabel txtHarga;
    private javax.swing.JTextField txtID;
    private javax.swing.JLabel txtIdProduk;
    private javax.swing.JLabel txtJumlah;
    private javax.swing.JLabel txtJumlahBayar;
    private javax.swing.JLabel txtKembalian;
    private javax.swing.JLabel txtNamaProduk;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtkembalian;
    private javax.swing.JTextField txtproduk;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

}
